stages:
    - test
    - build

pyCodeStyle:
    stage: test
    image: cytopia/pycodestyle:latest
    script:
      - pycodestyle **/*.py --config=setup.cfg


build:
    stage: build
    image: docker:19.03.1
    services:
      - docker:19.03.1-dind
    only:
      - master
      - feature/backend
    before_script:
      - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    script:
      - docker build -t ${CI_REGISTRY_IMAGE} .
      - docker push ${CI_REGISTRY_IMAGE}
