stages:
    - test
    - build

pyCodeStyle:
    stage: test
    image: 
      name: cytopia/pycodestyle:latest
      entrypoint: [""]
    script:
      - pycodestyle --config=setup.cfg


pyLint:
    stage: test
    image: 
      name: cytopia/pylint:latest
      entrypoint: [""]
    script:
      - pylint models/*.py
      - pylint server/*.py
      - pylint *.py

build:
    stage: build
    image: docker:19.03.1
    services:
      - docker:19.03.1-dind
    only:
      - master
      - dev
    before_script:
      - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    script:
      - docker build -t ${CI_REGISTRY_IMAGE} .
      - docker push ${CI_REGISTRY_IMAGE}
