version: '3.5'
services:
  webapp_service:
    container_name: webapp_container
    restart: always
    image: registry.gitlab.com/emumba/devops/aws-bootcloud
    ports:
     - "127.0.0.1:5000:5000"
    env_file: .env
