version: '3.5'
services:
  webapp:
    container_name: webapp
    restart: always
    image: registry.gitlab.com/emumba/devops/aws-bootcloud
    build: .
    ports:
     - 5000:5000
    env_file: .env

  database:
    image: "postgres"
    env_file: .env
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data/

volumes:
  postgres-data:
