name: AWS Bootcloud workflow
on:
  push:
    branches:
      - dev
      - master
      - main
      - github-cicd
jobs:
  pyCodeStyle:
    runs-on: ubuntu-latest
    container:
      image: cytopia/pycodestyle:latest
    steps:
      - name: Checkout to branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Run Pycode Style commands
        run: pycodestyle --config=setup.cfg

  
  pyLint:
    runs-on: ubuntu-latest
    container:
      image: cytopia/pylint:latest
    needs: ['pyCodeStyle']
    steps:
      - name: Checkout to branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Run pyLint Style commands
        run: |
          pylint models/*.py
          pylint server/*.py
          pylint *.py
      
  build:
    runs-on: ubuntu-latest
    needs: ['pyCodeStyle', 'pyLint']
    steps:
      - name: Checkout to branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      
      - name: Build and push docker image to GCR
        run: |
          docker login registry.gitlab.com -u emumba1519 -p eMumba1519
          docker build -t registry.gitlab.com/emumba/devops/aws-bootcloud:github .
          docker push registry.gitlab.com/emumba/devops/aws-bootcloud:github

      
      
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}
      # - name: Build and Push to Dockerhub
      #   uses: mr-smithers-excellent/docker-build-push@v4
      #   with:
      #     image: ${{ github.repository }}
      #     tag: latest
      #     registry: docker.io
      #     username: ${{ secrets.DOCKERHUB_USER }}
      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.CR_PAT }}
      # - name: print variables
      #   run: |
      #     echo "actor ${{ github.repository }}"
          
      # - name: Build and push docker image to GCR
      #   run: |
      #     docker build -t ghcr.io/${{ github.repository }}:latest .
      #     docker push ghcr.io/${{ github.repository }}:latest

      # - name: Build and push docker image to GCR
      #   uses: mr-smithers-excellent/docker-build-push@v4
      #   with:
      #     image: aws-bootcloud/aws-bootcloud
      #     tag: latest
      #     registry: ghcr.io
      #     githubOrg: emumba-com
      #     username: imtiaz-emumba
      #     password: ${{ secrets.CR_PAT }} 
      

      